services:
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - '4080:4080'
    volumes:
      - ./data:/var/lib/zinc
    restart: on-failure

  api:
    build:
      context: ../mail_api
      args:
        # - PORT=:8080
        - PORT=:443
        - GIN_MODE=release
    environment:
      - PORT=${ZINC_PORT}
      - APP_NAME=${ZINC_NAME}
      - ZINCSEARCH_HOST=${ZINC_HOST}
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      # - 8080:8080
      - 443:443
    depends_on:
      - zinc
    restart: on-failure
    volumes:
      - ./mail_tools:/usr/src/app